# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /array/shared/home/kmessan/k_means_CUDA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /array/shared/home/kmessan/k_means_CUDA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /array/shared/home/kmessan/k_means_CUDA/CMakeFiles /array/shared/home/kmessan/k_means_CUDA//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /array/shared/home/kmessan/k_means_CUDA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kmeans_seq

# Build rule for target.
kmeans_seq: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kmeans_seq
.PHONY : kmeans_seq

# fast build rule for target.
kmeans_seq/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmeans_seq.dir/build.make CMakeFiles/kmeans_seq.dir/build
.PHONY : kmeans_seq/fast

#=============================================================================
# Target rules for targets named kmeans_par

# Build rule for target.
kmeans_par: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kmeans_par
.PHONY : kmeans_par

# fast build rule for target.
kmeans_par/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmeans_par.dir/build.make CMakeFiles/kmeans_par.dir/build
.PHONY : kmeans_par/fast

kmeans_parallel.o: kmeans_parallel.cu.o
.PHONY : kmeans_parallel.o

# target to build an object file
kmeans_parallel.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmeans_par.dir/build.make CMakeFiles/kmeans_par.dir/kmeans_parallel.cu.o
.PHONY : kmeans_parallel.cu.o

kmeans_parallel.i: kmeans_parallel.cu.i
.PHONY : kmeans_parallel.i

# target to preprocess a source file
kmeans_parallel.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmeans_par.dir/build.make CMakeFiles/kmeans_par.dir/kmeans_parallel.cu.i
.PHONY : kmeans_parallel.cu.i

kmeans_parallel.s: kmeans_parallel.cu.s
.PHONY : kmeans_parallel.s

# target to generate assembly for a file
kmeans_parallel.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmeans_par.dir/build.make CMakeFiles/kmeans_par.dir/kmeans_parallel.cu.s
.PHONY : kmeans_parallel.cu.s

kmeans_sequential.o: kmeans_sequential.cpp.o
.PHONY : kmeans_sequential.o

# target to build an object file
kmeans_sequential.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmeans_seq.dir/build.make CMakeFiles/kmeans_seq.dir/kmeans_sequential.cpp.o
.PHONY : kmeans_sequential.cpp.o

kmeans_sequential.i: kmeans_sequential.cpp.i
.PHONY : kmeans_sequential.i

# target to preprocess a source file
kmeans_sequential.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmeans_seq.dir/build.make CMakeFiles/kmeans_seq.dir/kmeans_sequential.cpp.i
.PHONY : kmeans_sequential.cpp.i

kmeans_sequential.s: kmeans_sequential.cpp.s
.PHONY : kmeans_sequential.s

# target to generate assembly for a file
kmeans_sequential.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmeans_seq.dir/build.make CMakeFiles/kmeans_seq.dir/kmeans_sequential.cpp.s
.PHONY : kmeans_sequential.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... kmeans_par"
	@echo "... kmeans_seq"
	@echo "... kmeans_parallel.o"
	@echo "... kmeans_parallel.i"
	@echo "... kmeans_parallel.s"
	@echo "... kmeans_sequential.o"
	@echo "... kmeans_sequential.i"
	@echo "... kmeans_sequential.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

